---
title: "Overview"
---
# Securing Information 
Keeping information private has been a part of human history since the beginnings of society and spans every type of communication. Encoded messages have been used by oppressed social groups to unite a community,  by warring states to enact covert soldier movements (Enigma), by sociopaths in an attempt to boast their activities (Zodiac), and by the modern public performing personal/business transactions online (Hash). However, as forms of communication evolved, so has the ability to “crack” these codes. Therefore, more advanced forms of encryption are necessary in order to find the balance of protection and usability. A solution to this dilemma could be found in the maturing abilities of machine learning. Machine learning algorithms are becoming better at grouping characteristics between similar products (Recommender Systems), recognizing different faces (Image Recognition), and even making decisions in response to the current environment (Self-driving Vehicles). These capabilities are being accomplished using the available computational and cost resources. As a result, machine learning may offer the key to creating methods to protect our personal information while allowing us to take advantage of the electronic age.  

## Homomorphic Encryption
One form of protection that machine learning is assisting is in the form of homomorphic encryption. The concept of homomorphic encryption involves the ability to encode information and not require the need to decrypt it for transactional use. With this capacity, businesses and individuals could find comfort in expanding the use of more types of personal information which would also create new electronic opportunities for the public. 

This idea has been around since the release of one of the first public cryptosystems (RSA, 1977) but early attempts were not computationally viable or only allowed single-type transactions (addition or multiplication). However, the ideal goal is to embed the ability to perform all possible operations on encrypted data to eliminate the inherent security weakness of exposing the decrypted data in order to use it. This ability is known as fully homomorphic encryption (FTE) or cryptocomputing. Recently, research involving complex machine learning methods is gaining momentum in getting closer a solution. 

# Project Overview
As inspired by the advancements in developing a resource-efficient FHE scheme by utilizing machine learning and its ability to recognize patterns, this project will explore the use of machine learning techniques as applied to ciphertext cryptography to identify its ability to “unwind” the encryption pattern. In addition, this project will personally provide experience in text processing in both the Python and R programming environments. As a result of using multiple platforms (R and Python) as well as the computational time required to execute many of the actions, some code will not executed in this environment. Actual code can be found in other files included in this Github site. 

The project will consist of five stages which are available via the above tabs: Data, First Attempt, Second Attempt, and Third Attempt / Conclusion  

## Project Hypothesis
Current machine learning methods are capable of sophisticated pattern recognition (e.g. facial, handwriting, image, etc.) and can achieve a high degree of success in its predictions. This ability to recognize similar patterns in a given set of training data (e.g. images, product descriptions) could be utilized in a text-only environment. By identifying reoccurring textual “patterns” within encrypted text blocks and comparing them with known plain text examples, the machine learning model should produce adequate prediction results to match plain text sentences with their encrypted ciphertext equivalents. 

Caveat: Since cipher schemes are designed to resist decryption, I am not expecting a high success rate in prediction. 